version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

  phoenix:
    build: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: game_server_dev
      PGPORT: 5432
      PGHOST: postgres
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - postgres

volumes:
  postgres: