version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      PG_DATA: /data/postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

  phoenix:
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - postgres

volumes:
  postgres: